# Generated by Django 3.1.7 on 2022-03-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_1',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_10',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_11',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_12',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_2',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_3',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_4',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_5',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_6',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_7',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_8',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burner_9',
        ),
        migrations.RemoveField(
            model_name='temperatures',
            name='burnerzone',
        ),
        migrations.AddField(
            model_name='temperatures',
            name='addairox',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='addairoxA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='addairred',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='addairredA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_10A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_11A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_2A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_3A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_4A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_5A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_6A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_7A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_8A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='burnerz_9A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='dampcombair',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='dampcombairA',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='drexh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='dryerexhaust',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='dryerexhaustA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg1A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg2A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='eg3A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egfan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egfanA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egoxid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egoxidA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egprefire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egred',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egredA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='egtemp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='firingcurve',
            field=models.IntegerField(blank=True, null=True, verbose_name='Firing Curve #'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='flashtubes',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many flash tubes?'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairdryer',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairdryerA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairdrypress',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairdrypressA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairuds',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='freshairudsA',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairdamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairdampA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairde',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairdeA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairds',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairdsA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairfromlds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='hotairfromuds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='lds',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='ldsA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='ldsred',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='ldsredA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='postfire1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='postfire2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='postfire3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='postfire4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='prefire',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='product',
            field=models.TextField(default='Blank Testing', verbose_name='What is the product?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperatures',
            name='pushrate',
            field=models.FloatField(blank=True, null=True, verbose_name='Push Rate'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_22',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rec_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='redbz11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='redbz11A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rpdcl1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rpdcl1A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rpdcl2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Setpoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='rpdcl2A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='tempcoolrec',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds1',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds1A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds1red',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds1redA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds2',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds2A',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds2red',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='uds2redA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercarcool',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercarcoolA',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercarsuc',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercarsucA',
            field=models.IntegerField(blank=True, null=True, verbose_name='SetPoint'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercartemp1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercartemp2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercartemp3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AddField(
            model_name='temperatures',
            name='undercartemp4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatures'),
        ),
        migrations.AlterField(
            model_name='temperatures',
            name='user',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='User'),
        ),
    ]
