# Generated by Django 2.1.5 on 2021-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('burnerzone', models.IntegerField()),
                ('burner_1', models.IntegerField(blank=True)),
                ('burner_2', models.IntegerField(blank=True)),
                ('burner_3', models.IntegerField(blank=True)),
                ('burner_4', models.IntegerField(blank=True)),
                ('burner_5', models.IntegerField(blank=True)),
                ('burner_6', models.IntegerField(blank=True)),
                ('burner_7', models.IntegerField(blank=True)),
                ('burner_8', models.IntegerField(blank=True)),
                ('burner_9', models.IntegerField(blank=True)),
                ('burner_10', models.IntegerField(blank=True)),
                ('burner_11', models.IntegerField(blank=True)),
                ('burner_12', models.IntegerField(blank=True)),
            ],
        ),
    ]
