# Generated by Django 2.1.5 on 2021-03-25 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210325_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 25, 0, 23, 20, 162910)),
        ),
    ]
