# Generated by Django 2.1.5 on 2021-03-25 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210325_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 25, 0, 25, 27, 961895)),
        ),
    ]
