# Generated by Django 3.1.7 on 2021-04-02 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210325_0025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 4, 2)),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 2, 7, 31, 4, 76674, tzinfo=utc)),
        ),
    ]
